language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js: 
  - '12'
git:
  depth: 3
env:
  - DB=secure: "TZ/Bq8CL51VbHxSPBq+/Z2brP46G/vG2WB8eejGJ4CZ6cqrFN++N/gBnuprQcbXJSw485Xdl+lBcIIBeDdxgtfwiy8rwRMURXt94njBgZWuaeUeDPr87ygqFw7SoRZoTlTEROdM33KSsjG1bHMeT0S9NJlQrSeHEFupFkAgYsye9ypumcUdta6YNOlXVE1O8BhjCo6UlGoEGee0RMQAQi3uGdZzQUXUJiBX00zP1xNujwIJlqZAGTd5ZfoLfby4mJigyPk/LpJbCtTLw4RS0xRu/nMmgnZYJB57WWHLkTUhck8usvJr5Mb3nsGhcQIbv6yAfP5bdVRQfTyGkyVfvq7rmjy4AueQy0OsYyCDWMpAE+nTYg36Z8XVi4j0gSFQbR0sVxX1p0fjYLUSBzJsDM1TJ4u/zdSwn0efzYHGR2h4JOhozjxPfk9ncS4AdhCDbpnQm1fkP8uIYyH6Ltq5vDFeuEqgCfGMOcbB0DCOkZVFy2nxTesfgY5un/4GDrcYxxXkHLTflOQ2ys0ZLEQqIsQQCqCJ951/n2jYX4UtGk3X+yfJpXpdSNGKjswYHOg+6W5pSeBW4XXs0uX80hQhWJGJA2vqsVkl6GgtDvJtxRJVxVQdmZXax24n1nWtOTqdaeKAG5WsEyzignermg1gFHzXcR/cXa62nvYyqpTyBqY4="
script:
  - yarn test
notifications:
  email:
    recipients:
      - chander.zap@gmail.com
    on_success: always
    on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key:
    secure: "TZY2gzyTA7VbGQ1d7sWA16MZtuYHp0AW4xLMyw7HMFoCa0I3Q7ifub4MDZvslBcwy+iP0It8GMm6D0mTIbZTFb+TylAIpEDCl1u+jP1cOykYbfi5RY7SLt4Gf9+9df8R+UUJX/ZHjm3L7itORpM2E8tdj0pUwjD/7+LJepgb9t9ZbwzQJWLGHjNRiORYEyU/BfjX26duWFpfIpbrCbcPaShgoOR7wPKDCQJ23r1Cj1FweodNiQ9jkNGw28A0F/d3EjrYbOpxPWgJCoQbrmC9XEqPTuZUDpsc1VBUCuJAn5QtZI1GcRE5Gq3XXvqdktV8Rtr7sFvzO0GpBkW3J0c/2ZDPGs/1Ghv41j9jhYj1pnKvxahe5YfRozwyOSC5ZynwhstrVVCDQ6v45P4t9QpgB+DIRzlwbGMwJxlZnW25r/87BmxebQ/A22pBo5VwX+qKSRiKRyJxddfZzX6FKilycaIdzyA9p+5dazk9NZKrsES6q2BJGbeJGXDdgHaSSYasTA0B3zfl4OCTqmzBjYGSSbDtOCqRO2OfEVSg8VEd3AnzfWq7DdZBFdq8il0CktmmgWhbVIDR1mT6m5m6JqSJSC3H/sahcb//fu8PQZEMLIzydcsB0DBHBLbnFmuUGkSR+XS0UrpObrWiiR2zkihHWrsc82+29qUspZl6SQBzc0s="
  app: coding-challenge-flink
  on:
    repo: ByChanderZap/f-coding-int

